tools:
  - class_name: verl.tools.image_zoom_in_tool.ImageZoomInTool
    config:
      num_workers: 120
      rate_limit: 120
      timeout: 30
      type: native
    tool_schema:
      type: function
      function:
        name: image_zoom_in_tool
        description: Zoom in on a specific region of an image by cropping it based on a bounding box (bbox) and an optional object label.
        parameters:
          type: object
          properties:
            bbox_2d:
              type: array
              items:
                type: number
              minItems: 4
              maxItems: 4
              description: The bounding box of the region to zoom in, as [x1, y1, x2, y2], where (x1, y1) is the top-left corner and (x2, y2) is the bottom-right corner. It should satisfy x2>x1 and y2>y1.
            label:
              type: string
              description: The name or label of the object in the specified bounding box (optional).
          required: 
            - bbox_2d

  - class_name: verl.tools.map_tool.AmapInputTipsTool
    config:
      url: http://127.0.0.1:8001/amap_input_tips
      num_workers: 120
      rate_limit: 60
      timeout: 30
      type: native
    tool_schema:
      type: function
      function:
        name: amap_input_tips
        description: 搜索中国地点，获取相关POI建议
        parameters:
          type: object
          properties:
            query:
              type: string
              description: 想要搜索的任意地点关键词
          required: 
            - query
  
  - class_name: verl.tools.map_tool.AmapKeywordSearchTool
    config:
      url: http://127.0.0.1:8001/amap_keyword_search
      num_workers: 120
      rate_limit: 60
      timeout: 30
      type: native
    tool_schema:
      type: function
      function:
        name: amap_keyword_search
        description: 根据关键词进行搜索，搜索中国的POI
        parameters:
          type: object
          properties:
            query:
              type: string
              description: 需要查询的关键词
          required:
            - query

  - class_name: verl.tools.map_tool.AmapPOIDetailTool
    config:
      url: http://127.0.0.1:8001/amap_poi_detail
      num_workers: 120
      rate_limit: 60
      timeout: 30
      type: native
    tool_schema:
      type: function
      function:
        name: amap_poi_detail
        description: 根据中国的POI ID获取详细位置信息
        parameters:
          type: object
          properties:
            query:
              type: string
              description: 需要查询的POI ID
          required: 
            - query

  - class_name: verl.tools.map_tool.AmapStaticMapTool
    config:
      url: http://127.0.0.1:8001/amap_static_map
      num_workers: 120
      rate_limit: 5
      timeout: 30
      type: native
    tool_schema:
      type: function
      function:
        name: amap_static_map
        description: 根据经纬度，返回一个静态地图，包含附近一小片区域，以便近一步判断该地点。注意只能查询中国区域
        parameters:
          type: object
          properties:
            latitude:
              type: number
              description: 查询地点的纬度，用正/负值表示北/南纬，例如39.9042
            longitude:
              type: number
              description: 查询地点的经度，用正/负值表示东/西经，例如116.4074
          required: 
            - latitude
            - longitude

  - class_name: verl.tools.map_tool.AmapSatelliteMapTool
    config:
      url: http://127.0.0.1:8001/amap_satellite_map
      num_workers: 120
      rate_limit: 5
      timeout: 30
      type: native
    tool_schema:
      type: function
      function:
        name: amap_satellite_map
        description: 根据经纬度，返回一个卫星地图，包含附近一小片区域，以便近一步判断该地点。注意只能查询中国区域
        parameters:
          type: object
          properties:
            latitude:
              type: number
              description: 查询地点的纬度，用正/负值表示北/南纬，例如39.9042
            longitude:
              type: number
              description: 查询地点的经度，用正/负值表示东/西经，例如116.4074
          required: 
            - latitude
            - longitude