tools:
  - class_name: verl.tools.image_zoom_in_tool.ImageZoomInTool
    config:
      num_workers: 120
      rate_limit: 120
      timeout: 30
      type: native
    tool_schema:
      type: function
      function:
        name: image_zoom_in_tool
        description: Zoom in on a specific region of an image by cropping it based on a bounding box (bbox) and an optional object label.
        parameters:
          type: object
          properties:
            bbox_2d:
              type: array
              items:
                type: number
              minItems: 4
              maxItems: 4
              description: The bounding box of the region to zoom in, as [x1, y1, x2, y2], where (x1, y1) is the top-left corner and (x2, y2) is the bottom-right corner. It should satisfy x2>x1 and y2>y1.
            label:
              type: string
              description: The name or label of the object in the specified bounding box (optional).
          required: 
            - bbox_2d

  - class_name: verl.tools.map_tool.GoogleSearchTool
    config:
      url: http://127.0.0.1:8001/google_search
      num_workers: 120
      rate_limit: 120
      timeout: 30
      type: native
    tool_schema:
      type: function
      function:
        name: web_search
        description: Search online using the language of the target content (Chinese for Chinese content, English for English content). Keep queries concise.
        parameters:
          type: object
          properties:
            query:
              type: string
              description: the keyword need to search
          required: 
            - query